---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: local
      hooks:
          - id: isort
            name: isort
            stages: [commit]
            language: system
            entry: poetry run isort
            types: [python]

          - id: black
            name: black
            stages: [commit]
            language: system
            entry: poetry run black --config pyproject.toml
            types: [python]

          - id: mypy
            name: mypy
            stages: [commit]
            language: system
            entry: poetry run mypy
            types: [python]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.1 # or other specific tag
      hooks:
          - id: yamlfmt
            args: [--mapping, '2']
